In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

df_dataset = pd.read_csv('files/clean_text.csv')
df_dataset = df_dataset.drop(['Unnamed: 0'], axis=1)
df_dataset.head()

tweet_content        keyword  \
0                                  mds nunca liberar     ['Nubank']   
1                             viciar bateria celular  ['Coca-cola']   
2  toda vez vejo lá conferir saldo certo juro tra...     ['Nubank']   
3                                       pedir serasi     ['Nubank']   
4        kayofeer acontecer mãe quase ano nada ainda     ['Nubank']   

            user_location  classified  
0                 Goiânia         0.0  
1      Balneário Camboriú         1.0  
2                    None         0.0  
3  Rio de Janeiro, Brasil         1.0  
4           Macaé, Brasil         1.0

In [2]:
# Bag of words
count_vectorizer = CountVectorizer(binary=True)
X = count_vectorizer.fit_transform(df_dataset['tweet_content'].values.astype('U'))

In [3]:
count_vectorizer.get_feature_names() # Vocabulário

['aaaaaa',
 'abandonar',
 'abençoar',
 'abismal',
 'abrir',
 'abro',
 'absurda',
 'absurdo',
 'abóbora',
 'acabar',
 'academia',
 'acaso',
 'aceitar',
 'acertar',
 'acerto',
 'acesso',
 'achar',
 'acho',
 'ackisamayra',
 'acontecer',
 'acordar',
 'acostumar',
 'acreditar',
 'acredito',
 'adiantar',
 'adidasbrasil',
 'adiirjr',
 'adir',
 'adoro',
 'afrontar',
 'agasalho',
 'agilizar',
 'agiotar',
 'agir',
 'agoniar',
 'agora',
 'agr',
 'agraciar',
 'agradecida',
 'agradeço',
 'aguardar',
 'aguardo',
 'aguentar',
 'agência',
 'ah',
 'ahah',
 'ahhh',
 'ahora',
 'aiii',
 'ainda',
 'aipords',
 'air',
 'ajuda',
 'ajudar',
 'ajude',
 'akbilbo',
 'akendall',
 'alar',
 'alexandreelf',
 'algo',
 'alguem',
 'algum',
 'alguma',
 'algumas',
 'alguns',
 'alguém',
 'ali',
 'aliexpress',
 'aliexpressbr',
 'alimentação',
 'all',
 'allstar',
 'alta',
 'alterar',
 'alto',
 'alwaysmeteoro',
 'além',
 'alô',
 'amar',
 'amaralgusman',
 'amazon',
 'amazonilio',
 'ambev',
 'ambiguo',
 'ameaçar',
 'america',
 

In [4]:
count_vectorizer.vocabulary_.get('comprar')

384

In [5]:
df_cv = pd.DataFrame(X.toarray(), columns = count_vectorizer.get_feature_names())
df_cv.head()

aaaaaa  abandonar  abençoar  abismal  abrir  abro  absurda  absurdo  \
0       0          0         0        0      0     0        0        0   
1       0          0         0        0      0     0        0        0   
2       0          0         0        0      0     0        0        0   
3       0          0         0        0      0     0        0        0   
4       0          0         0        0      0     0        0        0   

   abóbora  acabar  ...  ânimo  éo  época  ódio  óleo  ótima  ótimo  última  \
0        0       0  ...      0   0      0     0     0      0      0       0   
1        0       0  ...      0   0      0     0     0      0      0       0   
2        0       0  ...      0   0      0     0     0      0      0       0   
3        0       0  ...      0   0      0     0     0      0      0       0   
4        0       0  ...      0   0      0     0     0      0      0       0   

   únicas  único  
0       0      0  
1       0      0  
2       0      0  
3       0      0  
4       0      0  

[5 rows x 1783 columns]

## Separando em treino e teste

In [6]:
from sklearn.model_selection import train_test_split

X = X.toarray()
y = df_dataset['classified']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [7]:
from sklearn.naive_bayes import MultinomialNB

#Criando o Modelo Naive Bayes 
naive_bayes = MultinomialNB()

#.......Treinando o Modelo.......
naive_bayes.fit(X_train, y_train)

#Fazendo as previsões
naive_bayes_pred = naive_bayes.predict(X_test)

In [8]:
from sklearn.metrics import accuracy_score, confusion_matrix

#Calculando a acurácia
acc = accuracy_score(naive_bayes_pred, y_test)

#Matriz de confusão 
cm = confusion_matrix(naive_bayes_pred, y_test)

print("Acurácia do modelo", acc*100)
print("\nMatriz de confusão: \n", cm)

Acurácia do modelo 61.19402985074627

Matriz de confusão: 
 [[31 22]
 [30 51]]


In [9]:
nova_frase = ["ódio da nubank quando tem notificação e é propaganda ao invés de ser dinheiro caindo na minha conta"] 
teste = count_vectorizer.transform(nova_frase)
pred = naive_bayes.predict(teste)
print(pred)

[0.]


In [10]:
nova_frase2 = ["Chegou o meu cartão do @nubank. Tô amando a embalagem dele Cara sorridente com os olhos em forma de coração"] 
teste2 = count_vectorizer.transform(nova_frase2)
pred2 = naive_bayes.predict(teste2)
print(pred2)

[1.]


## Separando datasets por Keyword

In [11]:
df_nubank = df_dataset[['Nubank' in x for x in df_dataset['keyword']]]

In [12]:
df_nike = df_dataset[['Nike' in x for x in df_dataset['keyword']]]

In [13]:
df_shein = df_dataset[['SHEIN' in x for x in df_dataset['keyword']]]

In [59]:
nubank_count_vectorizer = CountVectorizer(binary=True)
#X_nubank = nubank_count_vectorizer.fit_transform(df_nubank['tweet_content'].values.astype('U'))
#X_nubank = X_nubank.toarray()

X_nubank = df_nubank['tweet_content']
y_nubank = df_nubank['classified']

X_train_nubank, X_test_nubank, y_train_nubank, y_test_nubank = train_test_split(X_nubank, y_nubank, test_size=0.3, 
                                                                                random_state=42, stratify=y_nubank)
X_train_nubank = nubank_count_vectorizer.fit_transform(X_train_nubank)
X_test_nubank = nubank_count_vectorizer.transform(X_test_nubank.values.astype('U'))

In [60]:
nike_count_vectorizer = CountVectorizer(binary=True)
#X_nike = nike_count_vectorizer.fit_transform(df_nike['tweet_content'].values.astype('U'))

X_nike = df_nike['tweet_content']
y_nike = df_nike['classified']

X_train_nike, X_test_nike, y_train_nike, y_test_nike = train_test_split(X_nike, y_nike, test_size=0.3, 
                                                                                random_state=42, stratify=y_nike)
X_train_nike = nike_count_vectorizer.fit_transform(X_train_nike.values.astype('U'))
X_test_nike = nike_count_vectorizer.transform(X_test_nike.values.astype('U'))

In [61]:
shein_count_vectorizer = CountVectorizer(binary=True)
#X_shein = shein_count_vectorizer.fit_transform(df_shein['tweet_content'].values.astype('U'))

X_shein = df_shein['tweet_content']
y_shein = df_shein['classified']

X_train_shein, X_test_shein, y_train_shein, y_test_shein = train_test_split(X_shein, y_shein, test_size=0.3, 
                                                                                random_state=42, stratify=y_shein)
X_train_shein = shein_count_vectorizer.fit_transform(X_train_shein.values.astype('U'))
X_test_shein = shein_count_vectorizer.transform(X_test_shein.values.astype('U'))

## Aplicando MultinomialNB - Nubank

In [62]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import f1_score

#Criando o Modelo Naive Bayes 
naive_bayes_nubank = MultinomialNB()
#.......Treinando o Modelo.......
naive_bayes_nubank.fit(X_train_nubank, y_train_nubank)
#Fazendo as previsões
naive_bayes_pred_nubank = naive_bayes_nubank.predict(X_test_nubank)

f_medida_nubank = f1_score(y_test_nubank, naive_bayes_pred_nubank)
cm_nubank = confusion_matrix(naive_bayes_pred_nubank, y_test_nubank)

print("F-medida:", f_medida_nubank*100)
print("\nMatriz de confusão: \n", cm_nubank)

F-medida: 43.99999999999999

Matriz de confusão: 
 [[28 19]
 [ 9 11]]


## Multinomial NB - Nike

In [63]:
#Criando o Modelo Naive Bayes 
naive_bayes_nike = MultinomialNB()
#.......Treinando o Modelo.......
naive_bayes_nike.fit(X_train_nike, y_train_nike)
#Fazendo as previsões
naive_bayes_pred_nike = naive_bayes_nike.predict(X_test_nike)

f_medida_nike = f1_score(y_test_nike, naive_bayes_pred_nike)
cm_nike = confusion_matrix(naive_bayes_pred_nike, y_test_nike)

print("F-medida:", f_medida_nike*100)
print("\nMatriz de confusão: \n", cm_nike)

F-medida: 65.625

Matriz de confusão: 
 [[11  9]
 [13 21]]


## MultinomialNB - SHEIN

In [64]:
#Criando o Modelo Naive Bayes 
naive_bayes_shein = MultinomialNB()
#.......Treinando o Modelo.......
naive_bayes_shein.fit(X_train_shein, y_train_shein)
#Fazendo as previsões
naive_bayes_pred_shein = naive_bayes_shein.predict(X_test_shein)

f_medida_shein = f1_score(y_test_shein, naive_bayes_pred_shein)
cm_shein = confusion_matrix(naive_bayes_pred_shein, y_test_shein)

print("F-medida:", f_medida_shein*100)
print("\nMatriz de confusão: \n", cm_shein)

F-medida: 75.75757575757576

Matriz de confusão: 
 [[ 5  3]
 [13 25]]


## LinearSVC - Nubank

In [65]:
from sklearn import svm

SVM = svm.SVC(C=1.0, kernel='linear')
SVM.fit(X_train_nubank, y_train_nubank)
predictions_SVM_nubank = SVM.predict(X_test_nubank)

f_medida_nubank_svm = f1_score(y_test_nubank, predictions_SVM_nubank)
cm_nubank_svm = confusion_matrix(predictions_SVM_nubank, y_test_nubank)

print("F-medida:", f_medida_nubank_svm*100)
print("\nMatriz de confusão: \n", cm_nubank_svm)

F-medida: 38.46153846153846

Matriz de confusão: 
 [[25 20]
 [12 10]]


## LinearSVC - Nike

In [66]:
SVM = svm.SVC(C=1.0, kernel='linear')
SVM.fit(X_train_nike, y_train_nike)
predictions_SVM_nike = SVM.predict(X_test_nike)

f_medida_nike_svm = f1_score(y_test_nike, predictions_SVM_nike)
cm_nike_svm = confusion_matrix(predictions_SVM_nike, y_test_nike)

print("F-medida:", f_medida_nike_svm*100)
print("\nMatriz de confusão: \n", cm_nike_svm)

F-medida: 65.71428571428571

Matriz de confusão: 
 [[ 7  7]
 [17 23]]


## LinearSVC - SHEIN

In [67]:
SVM = svm.SVC(C=1.0, kernel='linear')
SVM.fit(X_train_shein, y_train_shein)
predictions_SVM_shein = SVM.predict(X_test_shein)

f_medida_shein_svm = f1_score(y_test_shein, predictions_SVM_shein)
cm_shein_svm = confusion_matrix(predictions_SVM_shein, y_test_shein)

print("F-medida:", f_medida_shein_svm*100)
print("\nMatriz de confusão: \n", cm_shein_svm)

F-medida: 74.2857142857143

Matriz de confusão: 
 [[ 2  2]
 [16 26]]


## Random Forest - Nubank

In [68]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=42)
rfc.fit(X_train_nubank, y_train_nubank)
predictions_rfc_nubank = rfc.predict(X_test_nubank)

f_medida_nubank_rfc = f1_score(y_test_nubank, predictions_rfc_nubank)
cm_nubank_rfc = confusion_matrix(predictions_rfc_nubank, y_test_nubank)

print("F-medida:", f_medida_nubank_rfc*100)
print("\nMatriz de confusão: \n", cm_nubank_rfc)

F-medida: 30.769230769230766

Matriz de confusão: 
 [[34 24]
 [ 3  6]]


## Random Forest - Nike

In [69]:
rfc.fit(X_train_nike, y_train_nike)
predictions_rfc_nike = rfc.predict(X_test_nike)

f_medida_nike_rfc = f1_score(y_test_nike, predictions_rfc_nike)
cm_nike_rfc = confusion_matrix(predictions_rfc_nike, y_test_nike)

print("F-medida:", f_medida_nike_rfc*100)
print("\nMatriz de confusão: \n", cm_nike_rfc)

F-medida: 68.35443037974683

Matriz de confusão: 
 [[ 2  3]
 [22 27]]


## Random Forest - SHEIN

In [70]:
rfc.fit(X_train_shein, y_train_shein)
predictions_rfc_shein = rfc.predict(X_test_shein)

f_medida_shein_rfc = f1_score(y_test_shein, predictions_rfc_shein)
cm_shein_rfc = confusion_matrix(predictions_rfc_shein, y_test_shein)

print("F-medida:", f_medida_shein_rfc*100)
print("\nMatriz de confusão: \n", cm_shein_rfc)

F-medida: 75.67567567567568

Matriz de confusão: 
 [[ 0  0]
 [18 28]]


## KNN - Nubank

In [71]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
knn = KNeighborsClassifier(n_neighbors=1)

knn.fit(X_train_nubank, y_train_nubank)

predictions_knn_nubank = knn.predict(X_test_nubank)

f_medida_nubank_knn = f1_score(y_test_nubank, predictions_knn_nubank)
cm_nubank_knn = confusion_matrix(predictions_knn_nubank, y_test_nubank)

print("F-medida:", f_medida_nubank_knn*100)
print("\nMatriz de confusão: \n", cm_nubank_knn)

F-medida: 45.00000000000001

Matriz de confusão: 
 [[36 21]
 [ 1  9]]


## KNN - Nike

In [72]:
knn.fit(X_train_nike, y_train_nike)

predictions_knn_nike = knn.predict(X_test_nike)

f_medida_nike_knn = f1_score(y_test_nike, predictions_knn_nike)
cm_nike_knn = confusion_matrix(predictions_knn_nike, y_test_nike)

print("F-medida:", f_medida_nike_knn*100)
print("\nMatriz de confusão: \n", cm_nike_knn)

F-medida: 71.05263157894737

Matriz de confusão: 
 [[ 5  3]
 [19 27]]


## KNN - SHEIN

In [73]:
knn.fit(X_train_shein, y_train_shein)

predictions_knn_shein = knn.predict(X_test_shein)

f_medida_shein_knn = f1_score(y_test_shein, predictions_knn_shein)
cm_shein_knn = confusion_matrix(predictions_knn_shein, y_test_shein)

print("F-medida:", f_medida_shein_knn*100)
print("\nMatriz de confusão: \n", cm_shein_knn)

F-medida: 57.14285714285715

Matriz de confusão: 
 [[11 14]
 [ 7 14]]


# Aplicando os modelos no dataset inteiro

## Naive Bayes

In [26]:
#Criando o Modelo Naive Bayes 
naive_bayes = MultinomialNB()
#.......Treinando o Modelo.......
naive_bayes.fit(X_train, y_train)
#Fazendo as previsões
naive_bayes_pred = naive_bayes.predict(X_test)

f_medida = f1_score(y_test, naive_bayes_pred)
cm = confusion_matrix(naive_bayes_pred, y_test)

print("F-medida:", f_medida*100)
print("\nMatriz de confusão: \n", cm)

F-medida: 66.23376623376623

Matriz de confusão: 
 [[31 22]
 [30 51]]


## LinearSVC

In [27]:
SVM = svm.SVC(C=1.0, kernel='linear')
SVM.fit(X_train, y_train)
predictions_SVM = SVM.predict(X_test)

f_medida_svm = f1_score(y_test, predictions_SVM)
cm_svm = confusion_matrix(predictions_SVM, y_test)

print("F-medida:", f_medida_svm*100)
print("\nMatriz de confusão: \n", cm_svm)

F-medida: 66.25766871165644

Matriz de confusão: 
 [[25 19]
 [36 54]]


## RandomForest

In [28]:
rfc.fit(X_train, y_train)
predictions_rfc = rfc.predict(X_test)

f_medida_rfc = f1_score(y_test, predictions_rfc)
cm_rfc = confusion_matrix(predictions_rfc, y_test)

print("F-medida:", f_medida_rfc*100)
print("\nMatriz de confusão: \n", cm_rfc)

F-medida: 70.05649717514123

Matriz de confusão: 
 [[19 11]
 [42 62]]


## KNN

In [29]:
knn.fit(X_train, y_train)

predictions_knn = knn.predict(X_test)

f_medida_knn = f1_score(y_test, predictions_knn)
cm_knn = confusion_matrix(predictions_knn, y_test)

print("F-medida:", f_medida_knn*100)
print("\nMatriz de confusão: \n", cm_knn)

F-medida: 56.94444444444443

Matriz de confusão: 
 [[31 32]
 [30 41]]
